# Generated by Django 5.0 on 2023-12-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_valuer_config_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='valeur',
            field=models.BinaryField(),
        ),
    ]
